# -*- coding: utf-8 -*-
"""PickleFileMaker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2lucj0wxnSaqpwplHCh_dtu9j9bbj48
"""

import pickle
import glob

path = '/content/drive/My Drive/PickleFile_Question1/*.pickle'
flag=-1
all_pickle = {}
for file in glob.glob(path):
  try:
    flag=flag+1
    print(flag)
    infile = open(file, 'rb')
    best_model = pickle.load(infile)
    all_pickle[file] = best_model
  except:
    print("Some Problem")

output1 = open('/content/drive/My Drive/All_PickleFiles_Question1/Features_question1.pickle', 'wb')
pickle.dump(all_pickle,output1)